source "https://rubygems.org"

gem "jekyll", "~> 3.7"
gem "minimal-mistakes-jekyll", git: "https://github.com/mmistakes/minimal-mistakes.git", tag: "4.26.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Gems used only for github page's dependencies version
gem "kramdown-parser-gfm", "~> 1.1.0"
