source "https://rubygems.org"

gem "jekyll", "~> 3.7"
# gem "minimal-mistakes-jekyll", "~> 4.26.2"

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
  gem "jekyll-paginate-v2"
end

# Gems used only for github page's dependencies version
gem "kramdown-parser-gfm", "~> 1.1.0"
