source "https://rubygems.org"

gem "jekyll", "~> 3.7"

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-github-metadata"
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

gem "kramdown-parser-gfm", "~> 1.1.0"
